### ISSUE TITLE
Failure running “Autocomplete Foreign Key Fixture Reference (habtm)”.

### ISSUE THREAD

**Issue by hryamzik** [textmate/yaml.tmbundle#13]
I get the following error when press alt+escape.

```
/Users/user/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/lib/rails/text_mate.rb:54:in `method_missing': undefined method `filepath' for TextMate:Module (NoMethodError)
	from /Users/user/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/lib/rails/rails_path.rb:54:in `initialize'
	from /Users/user/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/bin/fixture_auto_complete.rb:10:in `new'
	from /Users/user/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/bin/fixture_auto_complete.rb:10:in `parse_line'
	from /Users/user/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/bin/fixture_auto_complete.rb:60
```

**Comment by infininight** [comment]
This would be an issue for the Rails bundle:

https://github.com/textmate/ruby-on-rails-tmbundle
